### ISSUE TITLE
tiles seem to be freed directly below player first

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab#22]
![holes](https://user-images.githubusercontent.com/1245084/57245133-6667bf00-703a-11e9-8031-51e411b8f0fa.png)

First tiles to remove should be far behind player..

**Comment by kb173** [comment]
Tiles should never be freed like this - they can only converge (show the lower LOD tile above them and delete themselves), so this is likely related to #25 and the potential causes described there, or potentially another unsafety when fetching images from the server.

I will review this again once the measures described in #25 have been taken.

**Comment by chrisgraf** [comment]
still there after #25 seems to be fixed

**Comment by kb173** [comment]
So tiles are still disappearing for you? Can you describe what exactly you do when that happens?
Perhaps you could also try going into walk-mode (shortcut G) when you're on such a tile - does it throw an error, or are you positioned on an (invisible) ground?

**Comment by chrisgraf** [comment]
yes at least once it happened again but this time he recovered from this state again.. I did nothing specific ... moving around a bit and then just waited

**Comment by kb173** [comment]
I can't seem to reproduce it anymore... next time it happens, can you check a few things:
- When you press G to go into walk mode, does it throw an error, are you far below the map or on a sensible ground location?
- Does the debugger or logger have any output at that moment that could be related?
- Was the missing tile exactly below you?
- Did it just fix itself after some time, or did you move closer to or further away from that tile?

**Comment by chrisgraf** [comment]
For the last point: it fixed itself (reloaded?).. no movement was involved .. rest will be checked upon occurance

**Comment by chrisgraf** [comment]
it happened again - I first had to change to 1st person view .. there the tile reapeared for a short time but then it went away again (see screenshot) .. it crashed shortly after I pressed G with 

![image](https://user-images.githubusercontent.com/1245084/57561432-ea4bdf00-738b-11e9-9b99-7152ed2fc708.png)

![image](https://user-images.githubusercontent.com/1245084/57561421-e029e080-738b-11e9-800f-92d3a45b916c.png)

the tile was exactly below the player

**Comment by kb173** [comment]
Huh, the tile is still visible on the minimap - this and the error suggest that the only problem was the heightmap... it would be interesting to know whether there was any error related to the image not being loaded correctly in the debugger or logger.

**Comment by kb173** [comment]
Since a few things have been fixed and changed, could you try reproducing this again? (Ideally with all logger and debugger output if it happens again)

**Comment by chrisgraf** [comment]
I got it today again with the latest version .. There is no related logger information afaik. He complains about missing height information, but this should not cause a tile to go away, right?

**Comment by kb173** [comment]
It might be related to the multithreading issue in the server we talked about, but I will investigate further, also with regards to the crash you got again in #25.

Just to clarify: The tile isn't necessarily gone - most likely, it's just that due to the missing height information, it got maximally high. This means that you're inside of the tile at that position, making it look like it's gone. (This is also why it seems to reappear when you move to / inside another tile)

**Comment by chrisgraf** [comment]
I still don't get the issue completely .. the multithreading issue which is partly fixed now is about vegetation data, so why does the client loose the height information and then remembers or reloads it as soon as I move? Can we prevent this information loss somehow?

**Comment by kb173** [comment]
After more testing, it seems like this problem is happening when the server isn't properly saving a newly generated tile. To properly handle this case on the client, we need to add a state for "done loading, but can't be displayed" to the WorldTile:

Currently, WorldTiles are either "loading" or "done loading and to be displayed". The "done loading" state needs to be set, since it means that the threads are done, so the tile can e.g. be deleted. However, there is currently no way to specify that the threads are done, but that the tile shouldn't be displayed - e.g. if an image was invalid which the tile requires to be displayed properly.

**Comment by chrisgraf** [comment]
The client part of this issue seems to be fixed - we have to check this on the test-server but is probably a configuration issue so closing this for now
